"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['main.py']
DATA_FILES = []
OPTIONS = {
    'argv_emulation': False,
    'packages': ['gnupg', 'tkinter', 'numpy'],
    'iconfile': 'icon.icns',
    'plist': {
        'CFBundleName': 'GnuPG',
        'CFBundleDisplayName': 'GnuPG',
        'CFBundleGetInfoString': "GnuPG",
        'CFBundleIdentifier': "com.eddydev.gnupg",
        'CFBundleVersion': "0.1.9",
        'CFBundleShortVersionString': "0.1.9",
        'CFBundleExecutable': "GnuPG",
        'CFBundleIconFile': "icon.icns",
        'CFBundleDocumentTypes': [
            {
                'CFBundleTypeName': "GnuPG",
                'CFBundleTypeRole': "Editor",
                'LSHandlerRank': "Owner",
                'LSItemContentTypes': [
                    "com.eddydev.gnupg"
                ]
            }
        ]
    }
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
